[0m16:35:09.454119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001862D096F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001862D097450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001862D096D50>]}


============================== 16:35:09.459134 | b62aeb6b-e841-4d8f-8829-61036cc3b050 ==============================
[0m16:35:09.459134 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:35:09.460116 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\mngyn\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init books_dbt', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:35:09.480474 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/mngyn/.dbt')}
[0m16:35:09.481465 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:35:09.483462 [debug] [MainThread]: Starter project path: C:\Users\mngyn\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m16:35:09.519340 [info ] [MainThread]: 
Your new dbt project "books_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:35:09.520336 [info ] [MainThread]: Setting up your profile.
[0m16:36:20.386003 [info ] [MainThread]: Profile books_dbt written to C:\Users\mngyn\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:36:20.388016 [debug] [MainThread]: Command `dbt init` succeeded at 16:36:20.388016 after 71.01 seconds
[0m16:36:20.388989 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018626574E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018626574F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186265742D0>]}
[0m16:36:20.390010 [debug] [MainThread]: Flushing usage events
[0m16:36:22.106351 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:39:37.690480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020356E570D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020356DFF550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020356E572D0>]}


============================== 16:39:37.694383 | 453fb293-0750-49cb-b63b-15d2c1c43895 ==============================
[0m16:39:37.694383 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:39:37.695382 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mngyn\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:39:37.695382 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mngyn\data_eng\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:39:37.696597 [debug] [MainThread]: Command `dbt run` failed at 16:39:37.696597 after 0.08 seconds
[0m16:39:37.697726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020356DFD090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203503A4F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020355963BD0>]}
[0m16:39:37.697726 [debug] [MainThread]: Flushing usage events
[0m16:39:38.829266 [debug] [MainThread]: An error was encountered while trying to flush usage events
